version: '3.8'

services:
  backend:
    image: scientific-recommender-backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./model_deployment:/app/model_deployment
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    image: scientific-recommender-frontend
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: scientific-network
